#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -e
set -o pipefail

if [ "$QL41K_DELETE_REPO" = "y" -o "$QL41K_DELETE_REPO" = "Y" ]
then
    rm -f /etc/yum.repos.d/QL41k.repo
fi
