#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -d /etc/yum.repos.d ] || exit -1

cat > /etc/yum.repos.d/QL41K.repo << EOF
[QL41K-$QL41K_VERSION]
name=QL41K-$QL41K_VERSION
type=rpm-md
baseurl=$QL41K_REPO/RPMS
gpgcheck=1
gpgkey=$QL41K_REPO/RPMS/RPM-GPG-QLGC-KEY
enabled=1
EOF
